In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
headers = ['ProgramAdministrator',	'ProgramName',	'FuelType',	'Sector',	'NetFuelSavingAcquired',	'FuelSavingsUnit',	'CumulativeNetEnergySavingsAcquiredAsOfDate']
df = pd.read_csv('NYEnergySaving.csv', names= headers, skiprows=1)
df = df.dropna()
df.head()

,ProgramAdministrator,ProgramName,FuelType,Sector,NetFuelSavingAcquired,FuelSavingsUnit,CumulativeNetEnergySavingsAcquiredAsOfDate
0,Central Hudson Gas & Electric Corporation,Expanded Residential HVAC Program,Electric,Residential,0.00,MWh,2019-12-31T00:00:00.000
1,Central Hudson Gas & Electric Corporation,Home Energy Reporting,Electric,Residential,74836.28,MWh,2019-12-31T00:00:00.000
2,Central Hudson Gas & Electric Corporation,Home Energy Reporting,Gas,Residential,97050.76,Dth,2019-12-31T00:00:00.000
3,Central Hudson Gas & Electric Corporation,Mid-Size Commercial Business Program,Electric,Commercial,35711.02,MWh,2019-12-31T00:00:00.000
4,Central Hudson Gas & Electric Corporation,Residential Appliance Recycling Program,Electric,Residential,19562.37,MWh,2019-12-31T00:00:00.000

In [22]:
df = df[df.NetFuelSavingAcquired != 0]
for i,row in df.iterrows():
    df['ProgramName'] = df['ProgramName'].str.replace('*', '')
df.head()

,ProgramAdministrator,ProgramName,FuelType,Sector,NetFuelSavingAcquired,FuelSavingsUnit,CumulativeNetEnergySavingsAcquiredAsOfDate
1,Central Hudson Gas & Electric Corporation,Home Energy Reporting,Electric,Residential,74836.280,MWh,2019-12-31T00:00:00.000
2,Central Hudson Gas & Electric Corporation,Home Energy Reporting,Gas,Residential,97050.760,Dth,2019-12-31T00:00:00.000
3,Central Hudson Gas & Electric Corporation,Mid-Size Commercial Business Program,Electric,Commercial,35711.020,MWh,2019-12-31T00:00:00.000
4,Central Hudson Gas & Electric Corporation,Residential Appliance Recycling Program,Electric,Residential,19562.370,MWh,2019-12-31T00:00:00.000
5,Central Hudson Gas & Electric Corporation,Residential HVAC Program,Electric,Residential,125.683,MWh,2019-12-31T00:00:00.000